<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="/static/img/favicon.png" rel="icon" type="image/png">

    <!-- Theme CSS -->
    <link href="https://freeaihub.oss-cn-beijing.aliyuncs.com/asset/css/theme.css" rel="stylesheet" type="text/css"/>
    <link href="https://freeaihub.oss-cn-beijing.aliyuncs.com/asset/css/style.css" rel="stylesheet" type="text/css"/>
    <title>Python3 错误和异常 - FreeAIHub</title>
  
    <style>
      #top_bar {
          /* background-color: #6e84a3;
          color: white;
          font: bold 12px Helvetica;
          padding: 6px 5px 4px 5px;
          border-bottom: 1px outset; */
      }
      #status {
          text-align: center;
      }
      #sendCtrlAltDelButton {
          position: fixed;
          top: 0px;
          right: 0px;
          border: 1px outset;
          padding: 5px 5px 4px 5px;
          cursor: pointer;
      }

      #screen {
          /* flex: 1;
          overflow: hidden; */
      }

  </style>

  </head>
  <body class="bg-light" style="padding-top: 84px;">
      <!-- NAVBAR
    ================================================== -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white border-bottom">
      <div class="container-fluid" style="height: 42px;">

        <!-- Brand -->
        <a class="navbar-brand" href="../index.html">

          <img src="https://freeaihub.oss-cn-beijing.aliyuncs.com/asset/images/freeaihub.svg" width="60%" alt="freeai logo">
        </a>

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="navbarCollapse">

          <!-- Toggler -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fe fe-x"></i>
          </button>

          <!-- Navigation -->
          <ul class="navbar-nav ml-auto">
         
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#banner">首页</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#banner">课程页面</a>
            </li>
            <li class="nav-item dropdown">
            
            </li>
          </ul>
        </div>

      </div>
    </nav>


    <!-- BREADCRUMB
    ================================================== -->
    <nav class="d-lg-none bg-gray-800">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col">
          </div>
          <div class="col-auto">
            <!-- Toggler -->
            <div class="navbar-dark">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenavCollapse" aria-controls="sidenavCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </nav>

    <!-- CONTENT
    ================================================== -->
    <section style="overflow: hidden;">
      <div class="container-fluid">
        <div class="row">

          <div class="col-12 col-lg-2 col-xl-2 px-lg-0 border-bottom border-bottom-lg-0 border-right-lg border-gray-300 sidenav sidenav-left">     
            <div class="collapse d-lg-block" id="sidenavCollapse">
              <div class="px-lg-5">
                <ul class="nav side-left">
                  <li><a href="./index.html"> 如何学习本课程 </a></li>
<li><a href="./intro.html"> Python 简介 </a></li>
<li><a href="./setup.html"> Pyhon3 环境搭建及运行 </a></li>
<li><a href="./syntax.html"> Python 基础语法 </a></li>
<li><a href="./operator.html"> Python3 运算符 </a></li>
<li><a href="./datatype.html"> Python3 基本数据类型 </a></li>
<li><a href="./string.html"> Python3 基本数据类型-字符串 </a></li>
<li><a href="./number.html"> Python3 基本数据类型-数字 </a></li>
<li><a href="./list.html"> Python3 基本数据类型-列表 </a></li>
<li><a href="./tuple.html"> Python3 基本数据类型-元组 </a></li>
<li><a href="./dict.html"> Python3 基本数据类型-字典 </a></li>
<li><a href="./set.html"> Python3 基本数据类型-集合 </a></li>
<li><a href="./datastructure.html"> Python3 数据结构 </a></li>
<li><a href="./logic.html"> Python3 逻辑判断 </a></li>
<li><a href="./loop.html"> Python3 循环语句 </a></li>
<li><a href="./iterator-generator.html"> Python3 迭代器与生成器 </a></li>
<li><a href="./function.html"> Python3 函数 </a></li>
<li><a href="./errors-execptions.html"> Python3 错误和异常 </a></li>
<li><a href="./class.html"> Python3 面向对象 </a></li>
<li><a href="./namespace-scope.html"> Python3 命名空间和作用域 </a></li>
<li><a href="./package.html"> Python3 模块 </a></li>
<li><a href="./stdlib.html"> Python3 标准库 </a></li>
                </ul>  

              </div>
            </div>


          </div>

          <div class="entry-cellcontent col-10 col-lg-10 col-xl-10 offset-lg-2 offset-xl-2">
          <h1>Python3 错误和异常</h1>
<p>作为 Python 初学者，在刚学习 Python 编程时，经常会看到一些报错信息，在前面我们没有提及，这章节我们会专门介绍。</p>
<p>Python 有两种错误很容易辨认：语法错误和异常。</p>
<p>Python <code>assert</code>（断言）用于判断一个表达式，在表达式条件为 false 的时候触发异常。</p>
<h2>语法错误</h2>
<p>Python 的语法错误或者称之为解析错，是初学者经常碰到的。</p>
<pre><code class="Python">while True print('Hello world') 
</code></pre>

<p>这个例子中，函数<code>print()</code>被检查到有错误，是它前面缺少了一个冒号<code>:</code> 。</p>
<p>语法分析器指出了出错的一行，并且在最先找到的错误的位置标记了一个小小的箭头。</p>
<h2>异常</h2>
<p>即便 Python 程序的语法是正确的，在运行它的时候，也有可能发生错误。运行期检测到的错误被称为异常。</p>
<p>大多数的异常都不会被程序处理，都以错误信息的形式展现在这里:</p>
<h4>练习：不同类型的异常</h4>
<pre><code class="Python">#ZeroDivisionError: division by zero
10 * (1/0)             # 0 不能作为除数，触发异常
</code></pre>

<pre><code class="Python">#NameError: name 'spam' is not defined
4 + spam*3             # spam 未定义，触发异常
</code></pre>

<pre><code class="Python">#TypeError: Can't convert 'int' object to str implicitly
'2' + 2               # int 不能与 str 相加，触发异常
</code></pre>

<p>异常以不同的类型出现，这些类型都作为信息的一部分打印出来: 例子中的类型有<code>ZeroDivisionError</code>，<code>NameError</code>和<code>TypeError</code>。</p>
<p>错误信息的前面部分显示了异常发生的上下文，并以调用栈的形式显示具体信息。</p>
<h2>异常处理</h2>
<h3>try/except</h3>
<p>异常捕捉可以使用<code>try/except</code>语句。</p>
<p><img alt="img" src="./images/try_except.png" /></p>
<p>以下例子中，让用户输入一个合法的整数，但是允许用户中断这个程序（使用 Control-C 或者操作系统提供的方法）。用户中断的信息会引发一个 <code>KeyboardInterrupt</code>异常。</p>
<h4>练习：Python异常处理try/except</h4>
<pre><code class="Python">while True:
    try:
        x = int(input(&quot;请输入一个数字: &quot;))
        break
    except ValueError:
        print(&quot;您输入的不是数字，请再次尝试输入！&quot;)
</code></pre>

<p>try 语句按照如下方式工作；
- 首先，执行<code>try</code> 子句（在关键字 <code>try</code> 和关键字 <code>except</code> 之间的语句）。
- 如果没有异常发生，忽略<code>except</code>子句，<code>try</code> 子句执行后结束。
- 如果在执行 <code>try</code> 子句的过程中发生了异常，那么 try 子句余下的部分将被忽略。如果异常的类型和 except 之后的名称相符，那么对应的<code>except</code>子句将被执行。
- 如果一个异常没有与任何的<code>except</code> 匹配，那么这个异常将会传递给上层的 <code>try</code>中。</p>
<p>一个 <code>try</code> 语句可能包含多个<code>except</code>子句，分别来处理不同的特定的异常。最多只有一个分支会被执行。</p>
<p>处理程序将只针对对应的 try 子句中的异常进行处理，而不是其他的<code>try</code>的处理程序中的异常。</p>
<p>一个<code>except</code>子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组，例如:</p>
<pre><code>except (RuntimeError, TypeError, NameError):
    pass
</code></pre>

<p>最后一个<code>except</code>子句可以忽略异常的名称，它将被当作通配符使用。你可以使用这种方法打印一个错误信息，然后再次把异常抛出。</p>
<pre><code class="Python">import sys

try:
    f = open('myfile.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print(&quot;OS error: {0}&quot;.format(err))
except ValueError:
    print(&quot;Could not convert data to an integer.&quot;)
except:
    print(&quot;Unexpected error:&quot;, sys.exc_info()[0])
    raise
</code></pre>

<h3>try/except...else</h3>
<p><code>try/except</code> 语句还有一个可选的<code>else</code>子句，如果使用这个子句，那么必须放在所有的 <code>except</code>子句之后。</p>
<p><code>else</code>子句将在<code>try</code>子句没有发生任何异常的时候执行。</p>
<p><img alt="img" src="./images/try_except_else.png" /></p>
<p>以下实例在 try 语句中判断文件是否可以打开，如果打开文件时正常的没有发生异常则执行 else 部分的语句，读取文件内容：</p>
<h4>练习：Python异常处理try/except...else</h4>
<pre><code class="Python">for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except IOError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
</code></pre>

<p>使用 else 子句比把所有的语句都放在<code>try</code>子句里面要好，这样可以避免一些意想不到，而<code>except</code>又无法捕获的异常。</p>
<p>异常处理并不仅仅处理那些直接发生在<code>try</code>子句中的异常，而且还能处理子句中调用的函数（甚至间接调用的函数）里抛出的异常。例如:</p>
<pre><code class="Python">def this_fails():
    x = 1/0

try:
    his_fails()
</code></pre>

<h3>try-finally 语句</h3>
<p><code>try-finally</code>语句无论是否发生异常都将执行最后的代码。</p>
<p><img alt="img" src="./images/try_except_else_finally.png" /></p>
<p>以下实例中<code>finally</code>语句无论异常是否发生都会执行：</p>
<h4>练习：Python异常处理try-finally</h4>
<pre><code class="Python">try:
    test()
except AssertionError as error:
    print(error)
else:
    try:
        with open('file.log') as file:
            read_data = file.read()
    except FileNotFoundError as fnf_error:
        print(fnf_error)
finally:
    print('这句话，无论异常是否发生都会执行。')
</code></pre>

<h2>抛出异常</h2>
<p>Python 使用<code>raise</code>语句抛出一个指定的异常。</p>
<p>raise语法格式如下：</p>
<p><code>raise [Exception [, args [, traceback]]]</code></p>
<p><img alt="img" src="./images/raise.png" /></p>
<h4>练习：Python异常处理抛出异常<code>raise</code></h4>
<p><code>raise</code>唯一的一个参数指定了要被抛出的异常。它必须是一个异常的实例或者是异常的类（也就是 Exception 的子类）。</p>
<pre><code class="Python">#如果`x`的值大于 5 就触发异常:
x = 10
if x &gt; 5:
    raise Exception('x 不能大于 5。x 的值为: {}'.format(x))
</code></pre>

<p>如果你只想知道这是否抛出了一个异常，并不想去处理它，那么一个简单的 raise 语句就可以再次把它抛出。</p>
<pre><code class="Python">try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    raise
</code></pre>

<h2>用户自定义异常</h2>
<p>你可以通过创建一个新的异常类来拥有自己的异常。异常类继承自 Exception 类，可以直接继承，或者间接继承</p>
<h4>练习：用户自定义异常</h4>
<pre><code class="Python">class MyError(Exception):
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)

try:
    raise MyError(2*2)
except MyError as e:

#My exception occurred, value: 4
raise MyError('oops!')
</code></pre>

<p>在这个例子中，类<code>Exception</code>默认的 <strong>init</strong>() 被覆盖。</p>
<p>当创建一个模块有可能抛出多种不同的异常时，一种通常的做法是为这个包建立一个基础异常类，然后基于这个基础类为不同的错误情况创建不同的子类:</p>
<pre><code class="Python">class Error(Exception):
    &quot;&quot;&quot;Base class for exceptions in this module.&quot;&quot;&quot;
    pass

class InputError(Error):
    &quot;&quot;&quot;Exception raised for errors in the input.

    Attributes:
        expression -- input expression in which the error occurred
        message -- explanation of the error
    &quot;&quot;&quot;

    def __init__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    &quot;&quot;&quot;Raised when an operation attempts a state transition that's not
    allowed.

    Attributes:
        previous -- state at beginning of transition
        next -- attempted new state
        message -- explanation of why the specific transition is not allowed
    &quot;&quot;&quot;

    def __init__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message
</code></pre>

<p>大多数的异常的名字都以<code>Error</code>结尾，就跟标准的异常命名一样。</p>
<h2>定义清理行为</h2>
<p>try 语句还有另外一个可选的子句，它定义了无论在任何情况下都会执行的清理行为。 </p>
<h4>练习：Python异常定义清理行为</h4>
<pre><code class="Python">try:
    raise KeyboardInterrupt
finally:
    print('Goodbye, world!')
</code></pre>

<p>以上例子不管<code>try</code>子句里面有没有发生异常，<code>finally</code> 子句都会执行。</p>
<p>如果一个异常在 <code>try</code> 子句里（或者在 <code>except</code> 和 <code>else</code> 子句里）被抛出，而又没有任何的 <code>except</code> 把它截住，那么这个异常会在 <code>finally</code> 子句执行后被抛出。</p>
<p>下面是一个更加复杂的例子（在同一个 try 语句里包含 except 和 finally 子句）:</p>
<pre><code class="Python">def divide(x, y):
    try:
        result = x / y
    except ZeroDivisionError:
        print(&quot;division by zero!&quot;)
    else:
        print(&quot;result is&quot;, result)
    finally:
        print(&quot;executing finally clause&quot;)

divide(2, 1)
divide(2, 0)
divide(&quot;2&quot;, &quot;1&quot;)
</code></pre>

<h2>预定义的清理行为</h2>
<p>一些对象定义了标准的清理行为，无论系统是否成功的使用了它，一旦不需要它了，那么这个标准的清理行为就会执行。</p>
<p>这面这个例子展示了尝试打开一个文件，然后把内容打印到屏幕上:</p>
<pre><code class="Python">for line in open(&quot;myfile.txt&quot;):
    print(line, end=&quot;&quot;)
</code></pre>

<p>以上这段代码的问题是，当执行完毕后，文件会保持打开状态，并没有被关闭。</p>
<p>关键词 with 语句就可以保证诸如文件之类的对象在使用完之后一定会正确的执行他的清理方法:</p>
<pre><code class="Python">with open(&quot;myfile.txt&quot;) as f:
    for line in f:
        print(line, end=&quot;&quot;)
</code></pre>

<p>以上这段代码执行完毕后，就算在处理过程中出问题了，文件 f 总是会关闭。</p>
          </div>
          <backend type="k"></backend>
          <code class=gatsby-kernelname data-language=python></code>
        </div> <!-- / .row -->
      </div>
      
    </section>

    <!-- JAVASCRIPT
    ================================================== -->
    <!-- Libs JS -->
    <script src="https://landkit.goodthemes.co/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="https://landkit.goodthemes.co/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Theme JS -->
    <script src="https://landkit.goodthemes.co/assets/js/theme.min.js"></script>
    <script src="https://cdn.freeaihub.com/asset/js/cell.js"></script>
          
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script>
    MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]}
    };
    </script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
  </body>
</html>